### ISSUE TITLE
install blablado 

### ISSUE THREAD

**Issue by haesleinhuepf** [openUC2/Hackathon-UC2-LLM#1]
Hi @beniroquai ,

would you mind trying to install blablado on the control PC?
https://github.com/haesleinhuepf/blablado?tab=readme-ov-file#installation

You will also need an OpenAI API key. 
https://openai.com/blog/openai-api

You can test the installation using this notebook:
https://github.com/haesleinhuepf/blablado/blob/main/demo/microscope_stage_demo.ipynb

Thanks!

Best,
Robert

**Comment by beniroquai** [comment]
Done.
