### ISSUE TITLE
Hacking Notes

### ISSUE THREAD

**Issue by beniroquai** [openUC2/Hackathon-UC2-LLM#2]
# install the environment

```bash
conda create -n hackJena2024 python
conda activate hackJena2024
conda install devbio-napari -c conda-forge
```

# Install dependencies for the LL-based analysis

Go here and follow the steps: https://haesleinhuepf.github.io/BioImageAnalysisNotebooks/07_prompt_engineering/readme.html

```bash
conda install mamba # probably only on windows?
mamba install devbio-napari -c conda-forge
mamba install openai==1.5.0 -c conda-forge
pip install langchain==0.0.350
pip install bia-bob
````

Install blablado
https://github.com/haesleinhuepf/blablado/blob/main/demo/microscope_stage_demo.ipynb

```bash
pip install blablado
```

**Comment by AaronRiSa** [comment]
/Users/ImSwitch/miniforge/condabin/mamba install devbio-napari -c conda-forge
